### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by harshrocks**
Just some easy instructions for installing the required modules.

### CODE REVIEW

**Comment by user2589** [comment]
`requirements.txt` is used internally by setup.py. In case anybody wants to install requirements manually, the correct command is `pip install -r requirements.txt`, which is a common practice in Python packages. Extra instructions in the same file will break both mechanisms.

**Comment by harshrocks** [comment]
Sorry man I didn't know that.

**Comment by harshrocks** [comment]
Trying to participate in hacktoberfest.

**Comment by user2589** [comment]
hey, this is a great initiative! I don't have any easy tasks on hand right now, but if you have couple days to spend on this, porting [tokyocabinet](https://github.com/leahfitch/python-tokyocabinet) to Python3 would be great. I started it here but didn't have time to complete: https://github.com/user2589/python-tokyocabinet

**Pull request closed without merging**
