### PR TITLE
MANIFEST.in: Create

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by user2589** [comment]
can you give a brief description of changes and what it will improve?

**Comment by jayvdb** [comment]
Currently the sdist uploaded on PyPI fails to install because https://github.com/CMUSTRUDEL/strudel.scraper/blob/01218fb/setup.py#L17 refers to requirements.txt which doesnt exist in the sdist.

I have also included other files which are needed by re-packagers.

**Comment by user2589** [comment]
Can you describe the environment to reproduce this problem? It seems to work for me and few other people around using this package.

**Comment by jayvdb** [comment]
@user2589

This was raised on v0.4.0, and it still occurs on v1.4.0

Download the sdist from PyPI, unpack it and see there is no requirements.txt.  Run the setup.py inside to see it fail.

**Pull request closed without merging**
